### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'sodium.so'

### ISSUE THREAD

**Issue by belfie13** [SjonHortensius/3v4l_org#9] opened 2024-04-10 06:53 UTC
https://3v4l.org/XmspO

get this output on first line

```
Warning: PHP Startup: Unable to load dynamic library 'sodium.so' (tried: /usr/lib/php/8.3.5/modules/sodium.so (libsodium.so.23: cannot open shared object file: No such file or directory), /usr/lib/php/8.3.5/modules/sodium.so.so (/usr/lib/php/8.3.5/modules/sodium.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by jrfnl** [comment] 2024-04-10 10:18
Confirmed: https://phpc.social/@jrf_nl/112243927612347262

**Comment by SjonHortensius** [comment] 2024-04-11 14:40
this was caused by the new debian major (required for the new libcurl required by master) in the build nspawn that wasn't properly included in the runner nspawn

fixed now - thanks for the report

**Closed by SjonHortensius** 2024-04-11 14:40 UTC

**Comment by belfie13** [comment] 2024-04-14 13:22
sweet! I helped, yay :D haha, have a good day!
