### ISSUE TITLE
Live preview is wrong

### ISSUE THREAD

**Issue by Bilge** [SjonHortensius/3v4l_org#20] opened 2024-08-01 08:49 UTC
How does live preview (not) work? The problems I'm seeing are that the results from live preview are bogus and you only get the real result after clicking the _eval()_ button. This is highly misleading and problematic.

### Examples

```php
echo PHP_INT_MAX * 10;
```

| Live-preview | eval(); |
|-|-|
| 21474836470 |     9.2233720368548E+19 |

```php
echo (int)(PHP_INT_MAX * 10);
```

| Live-preview | eval(); |
|-|-|
| -10 | 0 |

**Comment by SjonHortensius** [comment] 2024-08-01 10:33
As you no doubt concluded yourself, the live preview is 32 bits, the non-live are 64 bits - so this is basically a duplicate of #19 :)

**Closed by SjonHortensius** 2024-08-01 10:33 UTC

**Comment by Bilge** [comment] 2024-08-01 11:14
Actually, I had not concluded that, so thanks for the clarification. But my question about live preview still stands: how does it work?

I suppose I could try digging into the source, but I hoped it would be easier to just ask. The response seems near-realtime and I was just naturally curious how that was even possible?

**Comment by Bilge** [comment] 2024-08-01 12:19
I guess it's just using this: https://github.com/seanmorris/php-wasm.

**Comment by SjonHortensius** [comment] 2024-08-01 12:57
> I guess it's just using this: https://github.com/seanmorris/php-wasm.

correct although until [recently](https://github.com/SjonHortensius/3v4l_org/commit/399346f64492f570c4da9ff2fbfa09a4f7b6011c) I used something I build myself
