### ISSUE TITLE
WASM interpreter dying

### ISSUE THREAD

**Issue by aolko** [SjonHortensius/3v4l_org#13] opened 2024-07-17 18:03 UTC
as soon as you enter the site the textarea will say "busy" and the tab will start to horribly lag.
![](https://i.ibb.co/WVXjnN8/thorium-f-KOk-D6c-Pg6.png)
![](https://i.ibb.co/pLM54zg/thorium-h-Xfl-UAb-Cvl.png)
Here's the log:
https://justpaste.it/dvxg6
https://gist.github.com/aolko/1734165eebb790f08e1dd63cadd3d9a6

**Comment by SjonHortensius** [comment] 2024-07-17 18:06
thanks for your report. Can you please do a proper hard refresh and report back if that fixes it?

This seems to be a duplicate of #12 :)

**Comment by aolko** [comment] 2024-07-17 18:13
> thanks for your report. Can you please do a proper hard refresh and report back if that fixes it?
> 
> This seems to be a duplicate of #12 :)

it only works for a couple of second with the
```
<?php

```
textarea and then it reverts back to 
```
busy
```

**Comment by SjonHortensius** [comment] 2024-07-17 18:21
I've disabled the entire method instead of filtering for valid content, does that fix things for you?

**Comment by aolko** [comment] 2024-07-17 18:32
yup https://3v4l.org/lgPR0

**Comment by SjonHortensius** [comment] 2024-07-23 09:27
@aolko please reopen if this issue returns

**Closed by SjonHortensius** 2024-07-23 09:27 UTC
