### ISSUE TITLE
Fatal error: Cannot redeclare function (previously declared in php-wasm)

### ISSUE THREAD

**Issue by Krinkle** [SjonHortensius/3v4l_org#23] opened 2024-08-12 23:20 UTC
At <https://3v4l.org/#live>, when typing:

```php
function x() {
}
x();
```

And then adding anything above or below it, the preview starts failing:

```
Fatal error: Cannot redeclare x() (previously declared in php-wasm run script:4) in php-wasm run script on line 5
```

Browser: Firefox 128 on macOS.

**Comment by SjonHortensius** [comment] 2024-09-03 07:18
duplicate of  #18

**Closed by SjonHortensius** 2024-09-03 07:18 UTC
